### ISSUE TITLE
疑似无法对 ipv6 正确处理

### ISSUE THREAD

**Issue by huankong233** [huankong233/HkList-laravel#33]
![image](https://github.com/huankong233/94list-laravel/assets/49610758/32abdcae-27a5-487b-b8fe-5749bd996fe2)

**Comment by huankong233** [comment]
已提交[issues](https://github.com/guzzle/guzzle/issues/3191)

**Comment by Zxis233** [comment]
请问有什么办法不使用ipv6吗

**Comment by huankong233** [comment]
> 请问有什么办法不使用ipv6吗

如果解析服务器不包含 `ipv6` 应该返回的地址也不会是 `ipv6` 的

**Comment by Zxis233** [comment]
> > 请问有什么办法不使用ipv6吗
> 
> 如果解析服务器不包含 `ipv6` 应该返回的地址也不会是 `ipv6` 的

我在服务端设置了“ipv4”优先，但部分链接仍会解析为ipv6

**Comment by huankong233** [comment]
> > > 请问有什么办法不使用ipv6吗
> > 
> > 
> > 如果解析服务器不包含 `ipv6` 应该返回的地址也不会是 `ipv6` 的
> 
> 我在服务端设置了“ipv4”优先，但部分链接仍会解析为ipv6

那确实没什么办法了 [guzzle](https://github.com/guzzle/guzzle) 尚未回应是否解决

**Comment by huankong233** [comment]
> > > 请问有什么办法不使用ipv6吗
> > 
> > 
> > 如果解析服务器不包含 `ipv6` 应该返回的地址也不会是 `ipv6` 的
> 
> 我在服务端设置了“ipv4”优先，但部分链接仍会解析为ipv6

有试试看仅限 ipv4 吗🤔，我测试比较少，可能会有些奇奇怪怪的问题

**Comment by Zxis233** [comment]
> > > > 请问有什么办法不使用ipv6吗
> > > 
> > > 
> > > 如果解析服务器不包含 `ipv6` 应该返回的地址也不会是 `ipv6` 的
> > 
> > 
> > 我在服务端设置了“ipv4”优先，但部分链接仍会解析为ipv6
> 
> 有试试看仅限 ipv4 吗🤔，我测试比较少，可能会有些奇奇怪怪的问题

目前设置为`ipv4优先`尚未出现问题。我再测试下吧

**Comment by huankong233** [comment]
已提交修复方案

**Comment by Zxis233** [comment]
收到

**Comment by laoqijun1** [comment]
试着去掉ipv6地址和/b/直接下载看看？

**Comment by huankong233** [comment]
测试环境里没出来过 `ipv6` 的地址了，复现不出来了
